# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from delphi_esr_msgs/EsrVehicle1.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class EsrVehicle1(genpy.Message):
  _md5sum = "ccab5c3c9c182cced0afa3db1f83373f"
  _type = "delphi_esr_msgs/EsrVehicle1"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header header

# ESR vehicle1
float32     vehicle_speed
bool        speed_direction
float32     yaw_rate
bool        yaw_rate_valid
int16       radius_curvature
bool        steering_angle_valid
bool        steering_angle_sign
uint16      steering_angle
uint16      steering_angle_rate
bool        steering_angle_rate_sign

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['header','vehicle_speed','speed_direction','yaw_rate','yaw_rate_valid','radius_curvature','steering_angle_valid','steering_angle_sign','steering_angle','steering_angle_rate','steering_angle_rate_sign']
  _slot_types = ['std_msgs/Header','float32','bool','float32','bool','int16','bool','bool','uint16','uint16','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,vehicle_speed,speed_direction,yaw_rate,yaw_rate_valid,radius_curvature,steering_angle_valid,steering_angle_sign,steering_angle,steering_angle_rate,steering_angle_rate_sign

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(EsrVehicle1, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.vehicle_speed is None:
        self.vehicle_speed = 0.
      if self.speed_direction is None:
        self.speed_direction = False
      if self.yaw_rate is None:
        self.yaw_rate = 0.
      if self.yaw_rate_valid is None:
        self.yaw_rate_valid = False
      if self.radius_curvature is None:
        self.radius_curvature = 0
      if self.steering_angle_valid is None:
        self.steering_angle_valid = False
      if self.steering_angle_sign is None:
        self.steering_angle_sign = False
      if self.steering_angle is None:
        self.steering_angle = 0
      if self.steering_angle_rate is None:
        self.steering_angle_rate = 0
      if self.steering_angle_rate_sign is None:
        self.steering_angle_rate_sign = False
    else:
      self.header = std_msgs.msg.Header()
      self.vehicle_speed = 0.
      self.speed_direction = False
      self.yaw_rate = 0.
      self.yaw_rate_valid = False
      self.radius_curvature = 0
      self.steering_angle_valid = False
      self.steering_angle_sign = False
      self.steering_angle = 0
      self.steering_angle_rate = 0
      self.steering_angle_rate_sign = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_fBfBh2B2HB().pack(_x.vehicle_speed, _x.speed_direction, _x.yaw_rate, _x.yaw_rate_valid, _x.radius_curvature, _x.steering_angle_valid, _x.steering_angle_sign, _x.steering_angle, _x.steering_angle_rate, _x.steering_angle_rate_sign))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 19
      (_x.vehicle_speed, _x.speed_direction, _x.yaw_rate, _x.yaw_rate_valid, _x.radius_curvature, _x.steering_angle_valid, _x.steering_angle_sign, _x.steering_angle, _x.steering_angle_rate, _x.steering_angle_rate_sign,) = _get_struct_fBfBh2B2HB().unpack(str[start:end])
      self.speed_direction = bool(self.speed_direction)
      self.yaw_rate_valid = bool(self.yaw_rate_valid)
      self.steering_angle_valid = bool(self.steering_angle_valid)
      self.steering_angle_sign = bool(self.steering_angle_sign)
      self.steering_angle_rate_sign = bool(self.steering_angle_rate_sign)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_fBfBh2B2HB().pack(_x.vehicle_speed, _x.speed_direction, _x.yaw_rate, _x.yaw_rate_valid, _x.radius_curvature, _x.steering_angle_valid, _x.steering_angle_sign, _x.steering_angle, _x.steering_angle_rate, _x.steering_angle_rate_sign))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 19
      (_x.vehicle_speed, _x.speed_direction, _x.yaw_rate, _x.yaw_rate_valid, _x.radius_curvature, _x.steering_angle_valid, _x.steering_angle_sign, _x.steering_angle, _x.steering_angle_rate, _x.steering_angle_rate_sign,) = _get_struct_fBfBh2B2HB().unpack(str[start:end])
      self.speed_direction = bool(self.speed_direction)
      self.yaw_rate_valid = bool(self.yaw_rate_valid)
      self.steering_angle_valid = bool(self.steering_angle_valid)
      self.steering_angle_sign = bool(self.steering_angle_sign)
      self.steering_angle_rate_sign = bool(self.steering_angle_rate_sign)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_fBfBh2B2HB = None
def _get_struct_fBfBh2B2HB():
    global _struct_fBfBh2B2HB
    if _struct_fBfBh2B2HB is None:
        _struct_fBfBh2B2HB = struct.Struct("<fBfBh2B2HB")
    return _struct_fBfBh2B2HB
