(cl:in-package sick_scan-msg)
(cl:export '(VERSION_NUMBER-VAL
          VERSION_NUMBER
          FIELD_INDEX-VAL
          FIELD_INDEX
          SYS_COUNT-VAL
          SYS_COUNT
          DIST_SCALE_FACTOR-VAL
          DIST_SCALE_FACTOR
          DIST_SCALE_OFFSET-VAL
          DIST_SCALE_OFFSET
          ANGLE_SCALE_FACTOR-VAL
          ANGLE_SCALE_FACTOR
          ANGLE_SCALE_OFFSET-VAL
          ANGLE_SCALE_OFFSET
          FIELD_RESULT_MRS-VAL
          FIELD_RESULT_MRS
          TIME_STATE-VAL
          TIME_STATE
          YEAR-VAL
          YEAR
          MONTH-VAL
          MONTH
          DAY-VAL
          DAY
          HOUR-VAL
          HOUR
          MINUTE-VAL
          MINUTE
          SECOND-VAL
          SECOND
          MICROSECOND-VAL
          MICROSECOND
))