(cl:in-package sick_scan-msg)
(cl:export '(UIIDENT-VAL
          UIIDENT
          UDISERIALNO-VAL
          UDISERIALNO
          BDEVICEERROR-VAL
          BDEVICEERROR
          BCONTAMINATIONWARNING-VAL
          BCONTAMINATIONWARNING
          BCONTAMINATIONERROR-VAL
          BCONTAMINATIONERROR
))