(cl:in-package sick_scan-msg)
(cl:export '(HEADER-VAL
          HEADER
          IMU-VAL
          IMU
          TICKS-VAL
          TICKS
          QUATERNION_ACCURACY-VAL
          QUATERNION_ACCURACY
          ANGULAR_VELOCITY_RELIABILITY-VAL
          ANGULAR_VELOCITY_RELIABILITY
          LINEAR_ACCELERATION_RELIABILITY-VAL
          LINEAR_ACCELERATION_RELIABILITY
))