Header header

# ESR status6
string      canmsg
uint8       supply1P8V
uint8       supplyN5V
uint8       waveDiffA2D
uint8       swVersionDSP3rdByte
bool        verticalAlginUpdated
uint8       systemPowerMode
bool        foundTarget
bool        recommendUnconverge
uint8       factoryAlginStatus1
uint8       factoryAlginStatus2
float32     factoryMisAlginment
uint8       servAlginUpdatesDone
float32     verticalMisAlginment

