Header header

# ESR vehicle2
uint16      scan_index_ack
bool        use_angle_misalignment
bool        clear_faults
int8        high_yaw_angle
bool        mr_only_transmit
bool        lr_only_transmit
float32     angle_misalignment
float32     lateral_mounting_offset
bool        radar_cmd_radiate
bool        blockage_disable
uint8       maximum_tracks
uint8       turn_signal_status
bool        vehicle_speed_valid
bool        mmr_upside_down
uint8       grouping_mode
bool        wiper_status
bool        raw_data_enabled
