Header header

# ESR vehicle3
bool        long_accel_valid
bool        lat_accel_valid
float32     lat_accel
float32     long_accel
uint8       radar_fov_lr
uint8       radar_fov_mr
bool        auto_align_disable
uint8       radar_height
bool        serv_align_type
bool        serv_align_enable
uint16      align_avg_ctr_total
bool        auto_align_converged
uint8       wheel_slip
uint8       serv_align_updates_need
int8        angle_mounting_offset

