// Generated by gencpp from file pointcloud_msgs/MsgPointCloud.msg
// DO NOT EDIT!


#ifndef POINTCLOUD_MSGS_MESSAGE_MSGPOINTCLOUD_H
#define POINTCLOUD_MSGS_MESSAGE_MSGPOINTCLOUD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <sensor_msgs/PointCloud2.h>

namespace pointcloud_msgs
{
template <class ContainerAllocator>
struct MsgPointCloud_
{
  typedef MsgPointCloud_<ContainerAllocator> Type;

  MsgPointCloud_()
    : header()
    , pointcloud()  {
    }
  MsgPointCloud_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , pointcloud(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::sensor_msgs::PointCloud2_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::sensor_msgs::PointCloud2_<ContainerAllocator> >::other >  _pointcloud_type;
  _pointcloud_type pointcloud;





  typedef boost::shared_ptr< ::pointcloud_msgs::MsgPointCloud_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pointcloud_msgs::MsgPointCloud_<ContainerAllocator> const> ConstPtr;

}; // struct MsgPointCloud_

typedef ::pointcloud_msgs::MsgPointCloud_<std::allocator<void> > MsgPointCloud;

typedef boost::shared_ptr< ::pointcloud_msgs::MsgPointCloud > MsgPointCloudPtr;
typedef boost::shared_ptr< ::pointcloud_msgs::MsgPointCloud const> MsgPointCloudConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pointcloud_msgs::MsgPointCloud_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pointcloud_msgs::MsgPointCloud_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pointcloud_msgs::MsgPointCloud_<ContainerAllocator1> & lhs, const ::pointcloud_msgs::MsgPointCloud_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.pointcloud == rhs.pointcloud;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pointcloud_msgs::MsgPointCloud_<ContainerAllocator1> & lhs, const ::pointcloud_msgs::MsgPointCloud_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pointcloud_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::pointcloud_msgs::MsgPointCloud_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pointcloud_msgs::MsgPointCloud_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pointcloud_msgs::MsgPointCloud_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pointcloud_msgs::MsgPointCloud_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pointcloud_msgs::MsgPointCloud_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pointcloud_msgs::MsgPointCloud_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pointcloud_msgs::MsgPointCloud_<ContainerAllocator> >
{
  static const char* value()
  {
    return "58155a63dc27a7cf7022c9a9af42b8dd";
  }

  static const char* value(const ::pointcloud_msgs::MsgPointCloud_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x58155a63dc27a7cfULL;
  static const uint64_t static_value2 = 0x7022c9a9af42b8ddULL;
};

template<class ContainerAllocator>
struct DataType< ::pointcloud_msgs::MsgPointCloud_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pointcloud_msgs/MsgPointCloud";
  }

  static const char* value(const ::pointcloud_msgs::MsgPointCloud_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pointcloud_msgs::MsgPointCloud_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"sensor_msgs/PointCloud2[] pointcloud\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/PointCloud2\n"
"# This message holds a collection of N-dimensional points, which may\n"
"# contain additional information such as normals, intensity, etc. The\n"
"# point data is stored as a binary blob, its layout described by the\n"
"# contents of the \"fields\" array.\n"
"\n"
"# The point cloud data may be organized 2d (image-like) or 1d\n"
"# (unordered). Point clouds organized as 2d images may be produced by\n"
"# camera depth sensors such as stereo or time-of-flight.\n"
"\n"
"# Time of sensor data acquisition, and the coordinate frame ID (for 3d\n"
"# points).\n"
"Header header\n"
"\n"
"# 2D structure of the point cloud. If the cloud is unordered, height is\n"
"# 1 and width is the length of the point cloud.\n"
"uint32 height\n"
"uint32 width\n"
"\n"
"# Describes the channels and their layout in the binary data blob.\n"
"PointField[] fields\n"
"\n"
"bool    is_bigendian # Is this data bigendian?\n"
"uint32  point_step   # Length of a point in bytes\n"
"uint32  row_step     # Length of a row in bytes\n"
"uint8[] data         # Actual point data, size is (row_step*height)\n"
"\n"
"bool is_dense        # True if there are no invalid points\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/PointField\n"
"# This message holds the description of one point entry in the\n"
"# PointCloud2 message format.\n"
"uint8 INT8    = 1\n"
"uint8 UINT8   = 2\n"
"uint8 INT16   = 3\n"
"uint8 UINT16  = 4\n"
"uint8 INT32   = 5\n"
"uint8 UINT32  = 6\n"
"uint8 FLOAT32 = 7\n"
"uint8 FLOAT64 = 8\n"
"\n"
"string name      # Name of field\n"
"uint32 offset    # Offset from start of point struct\n"
"uint8  datatype  # Datatype enumeration, see above\n"
"uint32 count     # How many elements in the field\n"
;
  }

  static const char* value(const ::pointcloud_msgs::MsgPointCloud_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pointcloud_msgs::MsgPointCloud_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.pointcloud);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MsgPointCloud_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pointcloud_msgs::MsgPointCloud_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pointcloud_msgs::MsgPointCloud_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "pointcloud[]" << std::endl;
    for (size_t i = 0; i < v.pointcloud.size(); ++i)
    {
      s << indent << "  pointcloud[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::sensor_msgs::PointCloud2_<ContainerAllocator> >::stream(s, indent + "    ", v.pointcloud[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // POINTCLOUD_MSGS_MESSAGE_MSGPOINTCLOUD_H
