(cl:in-package sick_scan-msg)
(cl:export '(UIVERSIONNO-VAL
          UIVERSIONNO
          RADARPREHEADERDEVICEBLOCK-VAL
          RADARPREHEADERDEVICEBLOCK
          RADARPREHEADERSTATUSBLOCK-VAL
          RADARPREHEADERSTATUSBLOCK
          RADARPREHEADERMEASUREMENTPARAM1BLOCK-VAL
          RADARPREHEADERMEASUREMENTPARAM1BLOCK
          RADARPREHEADERARRAYENCODERBLOCK-VAL
          RADARPREHEADERARRAYENCODERBLOCK
))