// Generated by gencpp from file msgs/MsgLidCamObject.msg
// DO NOT EDIT!


#ifndef MSGS_MESSAGE_MSGLIDCAMOBJECT_H
#define MSGS_MESSAGE_MSGLIDCAMOBJECT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace msgs
{
template <class ContainerAllocator>
struct MsgLidCamObject_
{
  typedef MsgLidCamObject_<ContainerAllocator> Type;

  MsgLidCamObject_()
    : header()
    , alpha(0.0)
    , pos_x(0.0)
    , pos_y(0.0)
    , track_id(0)  {
    }
  MsgLidCamObject_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , alpha(0.0)
    , pos_x(0.0)
    , pos_y(0.0)
    , track_id(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _alpha_type;
  _alpha_type alpha;

   typedef float _pos_x_type;
  _pos_x_type pos_x;

   typedef float _pos_y_type;
  _pos_y_type pos_y;

   typedef uint8_t _track_id_type;
  _track_id_type track_id;





  typedef boost::shared_ptr< ::msgs::MsgLidCamObject_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::msgs::MsgLidCamObject_<ContainerAllocator> const> ConstPtr;

}; // struct MsgLidCamObject_

typedef ::msgs::MsgLidCamObject_<std::allocator<void> > MsgLidCamObject;

typedef boost::shared_ptr< ::msgs::MsgLidCamObject > MsgLidCamObjectPtr;
typedef boost::shared_ptr< ::msgs::MsgLidCamObject const> MsgLidCamObjectConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::msgs::MsgLidCamObject_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::msgs::MsgLidCamObject_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::msgs::MsgLidCamObject_<ContainerAllocator1> & lhs, const ::msgs::MsgLidCamObject_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.alpha == rhs.alpha &&
    lhs.pos_x == rhs.pos_x &&
    lhs.pos_y == rhs.pos_y &&
    lhs.track_id == rhs.track_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::msgs::MsgLidCamObject_<ContainerAllocator1> & lhs, const ::msgs::MsgLidCamObject_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::msgs::MsgLidCamObject_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msgs::MsgLidCamObject_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msgs::MsgLidCamObject_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msgs::MsgLidCamObject_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msgs::MsgLidCamObject_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msgs::MsgLidCamObject_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::msgs::MsgLidCamObject_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7c8b7292cb11f95b4598c6ce61ded5f0";
  }

  static const char* value(const ::msgs::MsgLidCamObject_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7c8b7292cb11f95bULL;
  static const uint64_t static_value2 = 0x4598c6ce61ded5f0ULL;
};

template<class ContainerAllocator>
struct DataType< ::msgs::MsgLidCamObject_<ContainerAllocator> >
{
  static const char* value()
  {
    return "msgs/MsgLidCamObject";
  }

  static const char* value(const ::msgs::MsgLidCamObject_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::msgs::MsgLidCamObject_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float32 alpha\n"
"float32 pos_x           # obj_vcs_posx\n"
"float32 pos_y           # obj_vcs_posy\n"
"uint8 track_id\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::msgs::MsgLidCamObject_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::msgs::MsgLidCamObject_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.alpha);
      stream.next(m.pos_x);
      stream.next(m.pos_y);
      stream.next(m.track_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MsgLidCamObject_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::msgs::MsgLidCamObject_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::msgs::MsgLidCamObject_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "alpha: ";
    Printer<float>::stream(s, indent + "  ", v.alpha);
    s << indent << "pos_x: ";
    Printer<float>::stream(s, indent + "  ", v.pos_x);
    s << indent << "pos_y: ";
    Printer<float>::stream(s, indent + "  ", v.pos_y);
    s << indent << "track_id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.track_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MSGS_MESSAGE_MSGLIDCAMOBJECT_H
