// Generated by gencpp from file msgs/MsgRadCam.msg
// DO NOT EDIT!


#ifndef MSGS_MESSAGE_MSGRADCAM_H
#define MSGS_MESSAGE_MSGRADCAM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace msgs
{
template <class ContainerAllocator>
struct MsgRadCam_
{
  typedef MsgRadCam_<ContainerAllocator> Type;

  MsgRadCam_()
    : header()
    , num_overpass(0)  {
    }
  MsgRadCam_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , num_overpass(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _num_overpass_type;
  _num_overpass_type num_overpass;





  typedef boost::shared_ptr< ::msgs::MsgRadCam_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::msgs::MsgRadCam_<ContainerAllocator> const> ConstPtr;

}; // struct MsgRadCam_

typedef ::msgs::MsgRadCam_<std::allocator<void> > MsgRadCam;

typedef boost::shared_ptr< ::msgs::MsgRadCam > MsgRadCamPtr;
typedef boost::shared_ptr< ::msgs::MsgRadCam const> MsgRadCamConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::msgs::MsgRadCam_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::msgs::MsgRadCam_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::msgs::MsgRadCam_<ContainerAllocator1> & lhs, const ::msgs::MsgRadCam_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.num_overpass == rhs.num_overpass;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::msgs::MsgRadCam_<ContainerAllocator1> & lhs, const ::msgs::MsgRadCam_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::msgs::MsgRadCam_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msgs::MsgRadCam_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msgs::MsgRadCam_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msgs::MsgRadCam_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msgs::MsgRadCam_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msgs::MsgRadCam_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::msgs::MsgRadCam_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6c5400334bac6c91e919c72dca73df9e";
  }

  static const char* value(const ::msgs::MsgRadCam_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6c5400334bac6c91ULL;
  static const uint64_t static_value2 = 0xe919c72dca73df9eULL;
};

template<class ContainerAllocator>
struct DataType< ::msgs::MsgRadCam_<ContainerAllocator> >
{
  static const char* value()
  {
    return "msgs/MsgRadCam";
  }

  static const char* value(const ::msgs::MsgRadCam_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::msgs::MsgRadCam_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"uint8 num_overpass\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::msgs::MsgRadCam_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::msgs::MsgRadCam_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.num_overpass);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MsgRadCam_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::msgs::MsgRadCam_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::msgs::MsgRadCam_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "num_overpass: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.num_overpass);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MSGS_MESSAGE_MSGRADCAM_H
