// Generated by gencpp from file delphi_esr_msgs/EsrStatus3.msg
// DO NOT EDIT!


#ifndef DELPHI_ESR_MSGS_MESSAGE_ESRSTATUS3_H
#define DELPHI_ESR_MSGS_MESSAGE_ESRSTATUS3_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace delphi_esr_msgs
{
template <class ContainerAllocator>
struct EsrStatus3_
{
  typedef EsrStatus3_<ContainerAllocator> Type;

  EsrStatus3_()
    : header()
    , canmsg()
    , hwVersion(0)
    , interfaceVersion(0)
    , swVersionPld(0)
    , swVersionHost()
    , serialNum()  {
    }
  EsrStatus3_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , canmsg(_alloc)
    , hwVersion(0)
    , interfaceVersion(0)
    , swVersionPld(0)
    , swVersionHost(_alloc)
    , serialNum(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _canmsg_type;
  _canmsg_type canmsg;

   typedef uint8_t _hwVersion_type;
  _hwVersion_type hwVersion;

   typedef uint8_t _interfaceVersion_type;
  _interfaceVersion_type interfaceVersion;

   typedef uint8_t _swVersionPld_type;
  _swVersionPld_type swVersionPld;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _swVersionHost_type;
  _swVersionHost_type swVersionHost;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _serialNum_type;
  _serialNum_type serialNum;





  typedef boost::shared_ptr< ::delphi_esr_msgs::EsrStatus3_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::delphi_esr_msgs::EsrStatus3_<ContainerAllocator> const> ConstPtr;

}; // struct EsrStatus3_

typedef ::delphi_esr_msgs::EsrStatus3_<std::allocator<void> > EsrStatus3;

typedef boost::shared_ptr< ::delphi_esr_msgs::EsrStatus3 > EsrStatus3Ptr;
typedef boost::shared_ptr< ::delphi_esr_msgs::EsrStatus3 const> EsrStatus3ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::delphi_esr_msgs::EsrStatus3_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::delphi_esr_msgs::EsrStatus3_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::delphi_esr_msgs::EsrStatus3_<ContainerAllocator1> & lhs, const ::delphi_esr_msgs::EsrStatus3_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.canmsg == rhs.canmsg &&
    lhs.hwVersion == rhs.hwVersion &&
    lhs.interfaceVersion == rhs.interfaceVersion &&
    lhs.swVersionPld == rhs.swVersionPld &&
    lhs.swVersionHost == rhs.swVersionHost &&
    lhs.serialNum == rhs.serialNum;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::delphi_esr_msgs::EsrStatus3_<ContainerAllocator1> & lhs, const ::delphi_esr_msgs::EsrStatus3_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace delphi_esr_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::delphi_esr_msgs::EsrStatus3_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::delphi_esr_msgs::EsrStatus3_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::delphi_esr_msgs::EsrStatus3_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::delphi_esr_msgs::EsrStatus3_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::delphi_esr_msgs::EsrStatus3_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::delphi_esr_msgs::EsrStatus3_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::delphi_esr_msgs::EsrStatus3_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d267bafb7654adc3b6ab9a341e242e48";
  }

  static const char* value(const ::delphi_esr_msgs::EsrStatus3_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd267bafb7654adc3ULL;
  static const uint64_t static_value2 = 0xb6ab9a341e242e48ULL;
};

template<class ContainerAllocator>
struct DataType< ::delphi_esr_msgs::EsrStatus3_<ContainerAllocator> >
{
  static const char* value()
  {
    return "delphi_esr_msgs/EsrStatus3";
  }

  static const char* value(const ::delphi_esr_msgs::EsrStatus3_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::delphi_esr_msgs::EsrStatus3_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"# ESR status3\n"
"string      canmsg\n"
"uint8      hwVersion\n"
"uint8      interfaceVersion\n"
"uint8      swVersionPld\n"
"string      swVersionHost\n"
"string      serialNum\n"
"\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::delphi_esr_msgs::EsrStatus3_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::delphi_esr_msgs::EsrStatus3_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.canmsg);
      stream.next(m.hwVersion);
      stream.next(m.interfaceVersion);
      stream.next(m.swVersionPld);
      stream.next(m.swVersionHost);
      stream.next(m.serialNum);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EsrStatus3_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::delphi_esr_msgs::EsrStatus3_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::delphi_esr_msgs::EsrStatus3_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "canmsg: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.canmsg);
    s << indent << "hwVersion: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.hwVersion);
    s << indent << "interfaceVersion: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.interfaceVersion);
    s << indent << "swVersionPld: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.swVersionPld);
    s << indent << "swVersionHost: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.swVersionHost);
    s << indent << "serialNum: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.serialNum);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DELPHI_ESR_MSGS_MESSAGE_ESRSTATUS3_H
