(cl:in-package delphi_esr_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          LONG_ACCEL_VALID-VAL
          LONG_ACCEL_VALID
          LAT_ACCEL_VALID-VAL
          LAT_ACCEL_VALID
          LAT_ACCEL-VAL
          LAT_ACCEL
          LONG_ACCEL-VAL
          LONG_ACCEL
          RADAR_FOV_LR-VAL
          RADAR_FOV_LR
          RADAR_FOV_MR-VAL
          RADAR_FOV_MR
          AUTO_ALIGN_DISABLE-VAL
          AUTO_ALIGN_DISABLE
          RADAR_HEIGHT-VAL
          RADAR_HEIGHT
          SERV_ALIGN_TYPE-VAL
          SERV_ALIGN_TYPE
          SERV_ALIGN_ENABLE-VAL
          SERV_ALIGN_ENABLE
          ALIGN_AVG_CTR_TOTAL-VAL
          ALIGN_AVG_CTR_TOTAL
          AUTO_ALIGN_CONVERGED-VAL
          AUTO_ALIGN_CONVERGED
          WHEEL_SLIP-VAL
          WHEEL_SLIP
          SERV_ALIGN_UPDATES_NEED-VAL
          SERV_ALIGN_UPDATES_NEED
          ANGLE_MOUNTING_OFFSET-VAL
          ANGLE_MOUNTING_OFFSET
))