# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from delphi_esr_msgs/EsrStatus4.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class EsrStatus4(genpy.Message):
  _md5sum = "abec2ac03bbfc0ae47f593463cff96cc"
  _type = "delphi_esr_msgs/EsrStatus4"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header header

# ESR status4
string      canmsg
uint8       rollingCount3
uint8       mrlrMode
bool        patialBlockage
bool        sideLobeBlockage
bool        lrOnlyGratingLobeDet
bool        truckTargetDet
uint8       pathIdAcc
uint8       pathIdCmmbMove
uint8       pathIdCmmbStat
uint8       pathIdFcwMove
uint8       pathIdFcwStat
uint8       pathIdAccStat
float32     autoAlginAngle



================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['header','canmsg','rollingCount3','mrlrMode','patialBlockage','sideLobeBlockage','lrOnlyGratingLobeDet','truckTargetDet','pathIdAcc','pathIdCmmbMove','pathIdCmmbStat','pathIdFcwMove','pathIdFcwStat','pathIdAccStat','autoAlginAngle']
  _slot_types = ['std_msgs/Header','string','uint8','uint8','bool','bool','bool','bool','uint8','uint8','uint8','uint8','uint8','uint8','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,canmsg,rollingCount3,mrlrMode,patialBlockage,sideLobeBlockage,lrOnlyGratingLobeDet,truckTargetDet,pathIdAcc,pathIdCmmbMove,pathIdCmmbStat,pathIdFcwMove,pathIdFcwStat,pathIdAccStat,autoAlginAngle

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(EsrStatus4, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.canmsg is None:
        self.canmsg = ''
      if self.rollingCount3 is None:
        self.rollingCount3 = 0
      if self.mrlrMode is None:
        self.mrlrMode = 0
      if self.patialBlockage is None:
        self.patialBlockage = False
      if self.sideLobeBlockage is None:
        self.sideLobeBlockage = False
      if self.lrOnlyGratingLobeDet is None:
        self.lrOnlyGratingLobeDet = False
      if self.truckTargetDet is None:
        self.truckTargetDet = False
      if self.pathIdAcc is None:
        self.pathIdAcc = 0
      if self.pathIdCmmbMove is None:
        self.pathIdCmmbMove = 0
      if self.pathIdCmmbStat is None:
        self.pathIdCmmbStat = 0
      if self.pathIdFcwMove is None:
        self.pathIdFcwMove = 0
      if self.pathIdFcwStat is None:
        self.pathIdFcwStat = 0
      if self.pathIdAccStat is None:
        self.pathIdAccStat = 0
      if self.autoAlginAngle is None:
        self.autoAlginAngle = 0.
    else:
      self.header = std_msgs.msg.Header()
      self.canmsg = ''
      self.rollingCount3 = 0
      self.mrlrMode = 0
      self.patialBlockage = False
      self.sideLobeBlockage = False
      self.lrOnlyGratingLobeDet = False
      self.truckTargetDet = False
      self.pathIdAcc = 0
      self.pathIdCmmbMove = 0
      self.pathIdCmmbStat = 0
      self.pathIdFcwMove = 0
      self.pathIdFcwStat = 0
      self.pathIdAccStat = 0
      self.autoAlginAngle = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.canmsg
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_12Bf().pack(_x.rollingCount3, _x.mrlrMode, _x.patialBlockage, _x.sideLobeBlockage, _x.lrOnlyGratingLobeDet, _x.truckTargetDet, _x.pathIdAcc, _x.pathIdCmmbMove, _x.pathIdCmmbStat, _x.pathIdFcwMove, _x.pathIdFcwStat, _x.pathIdAccStat, _x.autoAlginAngle))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.canmsg = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.canmsg = str[start:end]
      _x = self
      start = end
      end += 16
      (_x.rollingCount3, _x.mrlrMode, _x.patialBlockage, _x.sideLobeBlockage, _x.lrOnlyGratingLobeDet, _x.truckTargetDet, _x.pathIdAcc, _x.pathIdCmmbMove, _x.pathIdCmmbStat, _x.pathIdFcwMove, _x.pathIdFcwStat, _x.pathIdAccStat, _x.autoAlginAngle,) = _get_struct_12Bf().unpack(str[start:end])
      self.patialBlockage = bool(self.patialBlockage)
      self.sideLobeBlockage = bool(self.sideLobeBlockage)
      self.lrOnlyGratingLobeDet = bool(self.lrOnlyGratingLobeDet)
      self.truckTargetDet = bool(self.truckTargetDet)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.canmsg
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_12Bf().pack(_x.rollingCount3, _x.mrlrMode, _x.patialBlockage, _x.sideLobeBlockage, _x.lrOnlyGratingLobeDet, _x.truckTargetDet, _x.pathIdAcc, _x.pathIdCmmbMove, _x.pathIdCmmbStat, _x.pathIdFcwMove, _x.pathIdFcwStat, _x.pathIdAccStat, _x.autoAlginAngle))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.canmsg = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.canmsg = str[start:end]
      _x = self
      start = end
      end += 16
      (_x.rollingCount3, _x.mrlrMode, _x.patialBlockage, _x.sideLobeBlockage, _x.lrOnlyGratingLobeDet, _x.truckTargetDet, _x.pathIdAcc, _x.pathIdCmmbMove, _x.pathIdCmmbStat, _x.pathIdFcwMove, _x.pathIdFcwStat, _x.pathIdAccStat, _x.autoAlginAngle,) = _get_struct_12Bf().unpack(str[start:end])
      self.patialBlockage = bool(self.patialBlockage)
      self.sideLobeBlockage = bool(self.sideLobeBlockage)
      self.lrOnlyGratingLobeDet = bool(self.lrOnlyGratingLobeDet)
      self.truckTargetDet = bool(self.truckTargetDet)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_12Bf = None
def _get_struct_12Bf():
    global _struct_12Bf
    if _struct_12Bf is None:
        _struct_12Bf = struct.Struct("<12Bf")
    return _struct_12Bf
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
