// Generated by gencpp from file radar_msgs/MsgRadar.msg
// DO NOT EDIT!


#ifndef RADAR_MSGS_MESSAGE_MSGRADAR_H
#define RADAR_MSGS_MESSAGE_MSGRADAR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <radar_msgs/MsgObject.h>
#include <radar_msgs/MsgObject.h>

namespace radar_msgs
{
template <class ContainerAllocator>
struct MsgRadar_
{
  typedef MsgRadar_<ContainerAllocator> Type;

  MsgRadar_()
    : header()
    , total_vehicles_left(0.0)
    , total_vehicles_right(0.0)
    , ObjectList_left()
    , ObjectList_right()  {
    }
  MsgRadar_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , total_vehicles_left(0.0)
    , total_vehicles_right(0.0)
    , ObjectList_left(_alloc)
    , ObjectList_right(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _total_vehicles_left_type;
  _total_vehicles_left_type total_vehicles_left;

   typedef float _total_vehicles_right_type;
  _total_vehicles_right_type total_vehicles_right;

   typedef std::vector< ::radar_msgs::MsgObject_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::radar_msgs::MsgObject_<ContainerAllocator> >::other >  _ObjectList_left_type;
  _ObjectList_left_type ObjectList_left;

   typedef std::vector< ::radar_msgs::MsgObject_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::radar_msgs::MsgObject_<ContainerAllocator> >::other >  _ObjectList_right_type;
  _ObjectList_right_type ObjectList_right;





  typedef boost::shared_ptr< ::radar_msgs::MsgRadar_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::radar_msgs::MsgRadar_<ContainerAllocator> const> ConstPtr;

}; // struct MsgRadar_

typedef ::radar_msgs::MsgRadar_<std::allocator<void> > MsgRadar;

typedef boost::shared_ptr< ::radar_msgs::MsgRadar > MsgRadarPtr;
typedef boost::shared_ptr< ::radar_msgs::MsgRadar const> MsgRadarConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::radar_msgs::MsgRadar_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::radar_msgs::MsgRadar_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::radar_msgs::MsgRadar_<ContainerAllocator1> & lhs, const ::radar_msgs::MsgRadar_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.total_vehicles_left == rhs.total_vehicles_left &&
    lhs.total_vehicles_right == rhs.total_vehicles_right &&
    lhs.ObjectList_left == rhs.ObjectList_left &&
    lhs.ObjectList_right == rhs.ObjectList_right;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::radar_msgs::MsgRadar_<ContainerAllocator1> & lhs, const ::radar_msgs::MsgRadar_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace radar_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::radar_msgs::MsgRadar_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::radar_msgs::MsgRadar_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::radar_msgs::MsgRadar_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::radar_msgs::MsgRadar_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::radar_msgs::MsgRadar_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::radar_msgs::MsgRadar_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::radar_msgs::MsgRadar_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a3c7315f9e8449ffdf3d76f6033062a8";
  }

  static const char* value(const ::radar_msgs::MsgRadar_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa3c7315f9e8449ffULL;
  static const uint64_t static_value2 = 0xdf3d76f6033062a8ULL;
};

template<class ContainerAllocator>
struct DataType< ::radar_msgs::MsgRadar_<ContainerAllocator> >
{
  static const char* value()
  {
    return "radar_msgs/MsgRadar";
  }

  static const char* value(const ::radar_msgs::MsgRadar_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::radar_msgs::MsgRadar_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float32 total_vehicles_left\n"
"float32 total_vehicles_right\n"
"MsgObject[] ObjectList_left\n"
"MsgObject[] ObjectList_right\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: radar_msgs/MsgObject\n"
"Header header\n"
"float32 range  # meters\n"
"float32 range_rate # velocity\n"
"float32 angle_centroid\n"
"float32 obj_vcs_posex\n"
"float32 obj_vcs_posey\n"
"uint8 track_id\n"
;
  }

  static const char* value(const ::radar_msgs::MsgRadar_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::radar_msgs::MsgRadar_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.total_vehicles_left);
      stream.next(m.total_vehicles_right);
      stream.next(m.ObjectList_left);
      stream.next(m.ObjectList_right);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MsgRadar_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::radar_msgs::MsgRadar_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::radar_msgs::MsgRadar_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "total_vehicles_left: ";
    Printer<float>::stream(s, indent + "  ", v.total_vehicles_left);
    s << indent << "total_vehicles_right: ";
    Printer<float>::stream(s, indent + "  ", v.total_vehicles_right);
    s << indent << "ObjectList_left[]" << std::endl;
    for (size_t i = 0; i < v.ObjectList_left.size(); ++i)
    {
      s << indent << "  ObjectList_left[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::radar_msgs::MsgObject_<ContainerAllocator> >::stream(s, indent + "    ", v.ObjectList_left[i]);
    }
    s << indent << "ObjectList_right[]" << std::endl;
    for (size_t i = 0; i < v.ObjectList_right.size(); ++i)
    {
      s << indent << "  ObjectList_right[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::radar_msgs::MsgObject_<ContainerAllocator> >::stream(s, indent + "    ", v.ObjectList_right[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // RADAR_MSGS_MESSAGE_MSGRADAR_H
