(cl:defpackage sick_scan-srv
  (:use )
  (:export
   "COLAMSGSRV"
   "<COLAMSGSRV-REQUEST>"
   "COLAMSGSRV-REQUEST"
   "<COLAMSGSRV-RESPONSE>"
   "COLAMSGSRV-RESPONSE"
   "ECRCHANGEARRSRV"
   "<ECRCHANGEARRSRV-REQUEST>"
   "ECRCHANGEARRSRV-REQUEST"
   "<ECRCHANGEARRSRV-RESPONSE>"
   "ECRCHANGEARRSRV-RESPONSE"
   "LIDOUTPUTSTATESRV"
   "<LIDOUTPUTSTATESRV-REQUEST>"
   "LIDOUTPUTSTATESRV-REQUEST"
   "<LIDOUTPUTSTATESRV-RESPONSE>"
   "LIDOUTPUTSTATESRV-RESPONSE"
  ))

