// Generated by gencpp from file radar_pa_msgs/radar_msg_A.msg
// DO NOT EDIT!


#ifndef RADAR_PA_MSGS_MESSAGE_RADAR_MSG_A_H
#define RADAR_PA_MSGS_MESSAGE_RADAR_MSG_A_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace radar_pa_msgs
{
template <class ContainerAllocator>
struct radar_msg_A_
{
  typedef radar_msg_A_<ContainerAllocator> Type;

  radar_msg_A_()
    : message(0)
    , ID(0)
    , distance(0.0)
    , velocity(0.0)
    , power(0.0)
    , angle(0.0)
    , is_target(0)
    , counter(0)  {
    }
  radar_msg_A_(const ContainerAllocator& _alloc)
    : message(0)
    , ID(0)
    , distance(0.0)
    , velocity(0.0)
    , power(0.0)
    , angle(0.0)
    , is_target(0)
    , counter(0)  {
  (void)_alloc;
    }



   typedef uint8_t _message_type;
  _message_type message;

   typedef uint32_t _ID_type;
  _ID_type ID;

   typedef float _distance_type;
  _distance_type distance;

   typedef float _velocity_type;
  _velocity_type velocity;

   typedef float _power_type;
  _power_type power;

   typedef float _angle_type;
  _angle_type angle;

   typedef uint8_t _is_target_type;
  _is_target_type is_target;

   typedef uint8_t _counter_type;
  _counter_type counter;





  typedef boost::shared_ptr< ::radar_pa_msgs::radar_msg_A_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::radar_pa_msgs::radar_msg_A_<ContainerAllocator> const> ConstPtr;

}; // struct radar_msg_A_

typedef ::radar_pa_msgs::radar_msg_A_<std::allocator<void> > radar_msg_A;

typedef boost::shared_ptr< ::radar_pa_msgs::radar_msg_A > radar_msg_APtr;
typedef boost::shared_ptr< ::radar_pa_msgs::radar_msg_A const> radar_msg_AConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::radar_pa_msgs::radar_msg_A_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::radar_pa_msgs::radar_msg_A_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::radar_pa_msgs::radar_msg_A_<ContainerAllocator1> & lhs, const ::radar_pa_msgs::radar_msg_A_<ContainerAllocator2> & rhs)
{
  return lhs.message == rhs.message &&
    lhs.ID == rhs.ID &&
    lhs.distance == rhs.distance &&
    lhs.velocity == rhs.velocity &&
    lhs.power == rhs.power &&
    lhs.angle == rhs.angle &&
    lhs.is_target == rhs.is_target &&
    lhs.counter == rhs.counter;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::radar_pa_msgs::radar_msg_A_<ContainerAllocator1> & lhs, const ::radar_pa_msgs::radar_msg_A_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace radar_pa_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::radar_pa_msgs::radar_msg_A_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::radar_pa_msgs::radar_msg_A_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::radar_pa_msgs::radar_msg_A_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::radar_pa_msgs::radar_msg_A_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::radar_pa_msgs::radar_msg_A_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::radar_pa_msgs::radar_msg_A_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::radar_pa_msgs::radar_msg_A_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6263190fa969f78dbbac8590a9a4d965";
  }

  static const char* value(const ::radar_pa_msgs::radar_msg_A_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6263190fa969f78dULL;
  static const uint64_t static_value2 = 0xbbac8590a9a4d965ULL;
};

template<class ContainerAllocator>
struct DataType< ::radar_pa_msgs::radar_msg_A_<ContainerAllocator> >
{
  static const char* value()
  {
    return "radar_pa_msgs/radar_msg_A";
  }

  static const char* value(const ::radar_pa_msgs::radar_msg_A_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::radar_pa_msgs::radar_msg_A_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8   message\n"
"uint32  ID\n"
"float32 distance\n"
"float32 velocity\n"
"float32 power\n"
"float32 angle\n"
"uint8   is_target\n"
"uint8   counter\n"
;
  }

  static const char* value(const ::radar_pa_msgs::radar_msg_A_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::radar_pa_msgs::radar_msg_A_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.message);
      stream.next(m.ID);
      stream.next(m.distance);
      stream.next(m.velocity);
      stream.next(m.power);
      stream.next(m.angle);
      stream.next(m.is_target);
      stream.next(m.counter);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct radar_msg_A_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::radar_pa_msgs::radar_msg_A_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::radar_pa_msgs::radar_msg_A_<ContainerAllocator>& v)
  {
    s << indent << "message: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.message);
    s << indent << "ID: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.ID);
    s << indent << "distance: ";
    Printer<float>::stream(s, indent + "  ", v.distance);
    s << indent << "velocity: ";
    Printer<float>::stream(s, indent + "  ", v.velocity);
    s << indent << "power: ";
    Printer<float>::stream(s, indent + "  ", v.power);
    s << indent << "angle: ";
    Printer<float>::stream(s, indent + "  ", v.angle);
    s << indent << "is_target: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_target);
    s << indent << "counter: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.counter);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RADAR_PA_MSGS_MESSAGE_RADAR_MSG_A_H
